name: x86_64 CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: ./setup.sh x86_64
    - name: update-shell
      run: . ~/.bashrc  
    - name: make
      run: make
